menu:
    Blog: /
    Archive: /archives/
    GitHub: github.com/stcatz
    About: /about/
    Rss: /atom.xml

favicon: /favicon.ico
logo: stcatz.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
